apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-from-cli-2-
spec:
  entrypoint: main
  templates:
  - name: main
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: [echo 'Hello Argo']