apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-from-cli-2-
spec:
  entrypoint: k8s-owner-reference
  templates:
  - name: k8s-owner-reference
    resource:
      action: create
      manifest: |
        apiVersion: v1
        kind: ConfigMap
        metadata:
          generateName: owned-eg
        data:
          some: value